<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>{{$merchant_name}}</h3><br />
    <h3>Daily Report - {{$report_date}}</h3>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td><b>NAME</b></td>
                <td><b>TIME IN</b></td>
                <td><b>TIME OUT</b></td>   
                <td><b>REGULAR HRS</b></td>   
                <td><b>OVERTIME</b></td> 
            </tr>
        </thead>
        <tbody>
            @foreach ($records as $record)
            <tr>
                <td>{{$record->name}}</td>
                <td>{{$record->time_in}}</td>
                <td>{{$record->time_out}}</td>
                <td>{{$record->regularhrs}}</td>
                <td>{{$record->overtimehrs}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div>
        This report is not final until the payroll period ends.<br/>
        <i>Generated by system on {{$generated_at}}</i>
    </div>
  </body>
</html>